In [4]:
import numpy as np
#1D Array
arr1 = np.array([1,2,3,4,5])
print(arr1)


[1 2 3 4 5]


In [6]:
#2D Array
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)


[[1 2 3]
 [4 5 6]]


In [8]:
#Array of zeros/Ones
zeros_arr = np.zeros((3,3))
print(zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
#Ones
ones_arr = np.ones((2,4))
print(ones_arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
#Array with range of Numbers
#using arange :
range_arr = np.arange(0,10,2)
print(range_arr)

[0 2 4 6 8]


In [14]:
#Using linspace(Generates numbers evenly spaced) :
linspace_arr = np.linspace(0,10,5)
print(linspace_arr)

[ 0.   2.5  5.   7.5 10. ]


In [16]:
#Reshape an Array
reshaped_arr = np.arange(12).reshape(3,4)
print(reshaped_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [18]:
#Basic Arithmetic Operations
#Addition:
arr_a = np.array([10,20,30])
arr_b = np.array([1,2,3])
add_arr = arr_a + arr_b
print(add_arr)

[11 22 33]


In [20]:
#Multiplication:
mult_arr = arr_a*arr_b
print(mult_arr)

[10 40 90]


In [22]:
#Division :
div_arr = arr_a/arr_b
print(div_arr)

[10. 10. 10.]


In [24]:
#Array Statistics 
#Mean:
mean_val = np.mean(arr1)
print(mean_val)

3.0


In [28]:
#Sum:
sum_val = np.sum(arr1)
print(sum_val)

15


In [30]:
#Standard Deviation:
std_val = np.std(arr1)
print(std_val)

1.4142135623730951


In [32]:
#Min/Max:
min_val = np.min(arr1)
max_val = np.max(arr1)
print(min_val,max_val)

1 5


In [36]:
#Indexing & Slicing
#Single Element:
element = arr1[2] #array = [1,2,3,4,5]
print(element)

3


In [38]:
#Slice
slice_arr = arr1[1:4]
print(slice_arr)

[2 3 4]


In [40]:
#2D Array Indexing:
element_2d = arr2[1,2]
print(element_2d)

6


In [42]:
#Matrix Multiplication:
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6],[7,8]])
matrix_mult = np.dot(matrix1,matrix2)
print(matrix_mult)

[[19 22]
 [43 50]]


In [44]:
#Transpose of a matrix
transpose_matrix = np.transpose(matrix1)
print(transpose_matrix)

[[1 3]
 [2 4]]


In [48]:
#Random numbers:
#Random integer:
rand_int = np.random.randint(1,10,size=(3,3))
print(rand_int)

[[2 8 3]
 [7 1 3]
 [1 1 6]]


In [50]:
#Random Float:
rand_float = np.random.rand(2,3)
print(rand_float)

[[0.20380739 0.38871919 0.76125554]
 [0.03707215 0.18898077 0.52511074]]


In [58]:
#Stacking Arrays :
#Horinzontal Stack:
h_stack = np.hstack((arr_a,arr_b)) #here, arr_a= [10,20,30], arr_b = [1,2,3]
print(h_stack)

[10 20 30  1  2  3]


In [62]:
#Vertical Stack:
v_stack = np.vstack((arr_a,arr_b)) #here, arr_a= [10,20,30], arr_b = [1,2,3]
print(v_stack)

[[10 20 30]
 [ 1  2  3]]


In [64]:
#Array Conditionals
#Condition:
condition_arr = arr_a > 15
print(condition_arr)

[False  True  True]


In [66]:
#Filter based on Condition:
filtered_arr = arr_a[arr_a > 15]
print(filtered_arr)

[20 30]
